/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Face_Detection;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.opencv.core.Core;
import org.opencv.core.Mat;
import org.opencv.core.MatOfByte;
import org.opencv.core.MatOfRect;
import org.opencv.core.Point;
import org.opencv.core.Rect;
import org.opencv.core.Scalar;
import org.opencv.core.Size;
import org.opencv.imgcodecs.Imgcodecs;
import org.opencv.imgproc.Imgproc;
import org.opencv.objdetect.CascadeClassifier;
import static org.opencv.objdetect.Objdetect.CASCADE_SCALE_IMAGE;
import org.opencv.videoio.VideoCapture;

/**
 *
 * @author Zed
 */
public class Main extends javax.swing.JFrame {
    
    String fIn;
//    String source = "C:\\javacv-resource\\opencv\\sources\\data\\haarcascades\\haarcascade_frontalface_alt.xml"; 
    String source = "xml/haarcascade_frontalface_alt2.xml";
    CascadeClassifier faceDetector = new CascadeClassifier(source);
    
    VideoCapture capture;

    
    public Main() {
        initComponents();
        bStop.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        imgPath = new javax.swing.JTextField();
        bSelect = new javax.swing.JButton();
        lImage = new javax.swing.JLabel();
        lJumlah = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bAbout = new javax.swing.JButton();
        bStop = new javax.swing.JButton();
        bCam = new javax.swing.JButton();
        bClose = new javax.swing.JButton();
        bStart = new javax.swing.JButton();

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Face Detection");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Image Path:");

        imgPath.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        imgPath.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 82, 107), 3));

        bSelect.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        bSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button1.png"))); // NOI18N
        bSelect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bSelectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bSelectMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bSelectMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bSelectMouseReleased(evt);
            }
        });
        bSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSelectActionPerformed(evt);
            }
        });

        lImage.setForeground(new java.awt.Color(255, 255, 255));
        lImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(72, 82, 107), 3));

        lJumlah.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lJumlah.setText(" ");

        jPanel2.setBackground(new java.awt.Color(72, 82, 107));

        bAbout.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        bAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button5.png"))); // NOI18N
        bAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bAboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bAboutMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bAboutMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bAboutMouseReleased(evt);
            }
        });
        bAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAboutActionPerformed(evt);
            }
        });

        bStop.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        bStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button3.png"))); // NOI18N
        bStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bStopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bStopMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bStopMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bStopMouseReleased(evt);
            }
        });
        bStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStopActionPerformed(evt);
            }
        });

        bCam.setBackground(new java.awt.Color(102, 204, 255));
        bCam.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        bCam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button2.png"))); // NOI18N
        bCam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 204, 255), 0));
        bCam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bCamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bCamMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bCamMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bCamMouseReleased(evt);
            }
        });
        bCam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCamActionPerformed(evt);
            }
        });

        bClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button6.png"))); // NOI18N
        bClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bCloseMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bCloseMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bCloseMouseReleased(evt);
            }
        });
        bClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bClose, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bStop, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCam, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(bAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170)
                .addComponent(bCam)
                .addGap(40, 40, 40)
                .addComponent(bStop, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addComponent(bClose, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        bStart.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        bStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button4.png"))); // NOI18N
        bStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bStartMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bStartMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bStartMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bStartMouseReleased(evt);
            }
        });
        bStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bStart, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(imgPath, javax.swing.GroupLayout.PREFERRED_SIZE, 432, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addComponent(bSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(imgPath, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(lImage, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bStart, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSelectActionPerformed
        
        try {
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File file = chooser.getSelectedFile();
            tampilkanGambar(file);
            
            fIn = file.getAbsolutePath();
            imgPath.setText(fIn);
        
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "File error");
        }
        
    }//GEN-LAST:event_bSelectActionPerformed

    
    private void tampilkanGambar(File gambar) {
        ImageIcon icon = new ImageIcon(gambar.toString());
        Image image = icon.getImage().getScaledInstance(lImage.getWidth(), lImage.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ic = new ImageIcon(image);
        lImage.setIcon(ic);
    }
    
    
    private void bStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStartActionPerformed
        
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        
        String imgFile = fIn;
        Mat src = Imgcodecs.imread(fIn);
        
        MatOfRect faceDetection = new MatOfRect();
        faceDetector.detectMultiScale(src, faceDetection);
        
        for(Rect rect: faceDetection.toArray()) {
            Imgproc.rectangle(src, new Point(rect.x, rect.y), new Point(rect.x + rect.width, rect.y + rect.height), new Scalar(0, 0, 255), 3);
        }

        String newPath = fIn.substring(0, fIn.lastIndexOf("/") + 1);
        Imgcodecs.imwrite(newPath + "output.jpg", src);
        File fOut = new File(newPath + "output.jpg");
        tampilkanGambar(fOut);
        fOut.deleteOnExit();
        
        int hasil = faceDetection.toArray().length;
        lJumlah.setText("Faces Detected: " + hasil);

    }//GEN-LAST:event_bStartActionPerformed

    private void bCamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCamActionPerformed

        lJumlah.setText("Faces detected 0");
        Thread wcam = new Thread() {
            public void run(){
                capture = new VideoCapture(0);//0 mean your default web cam
              
                MatOfRect rostros = new MatOfRect();
                MatOfByte mem = new MatOfByte();

                Mat frame = new Mat();
                Mat frame_gray = new Mat();

                Rect[] facesArray;      
                Graphics g;
                BufferedImage buff = null;
                
                
                while(capture.read(frame)){
                    if(frame.empty()){
                        break;
                    } else {
                        try {
                            g = lImage.getGraphics();
                            Imgproc.cvtColor(frame, frame_gray, Imgproc.COLOR_BGR2GRAY);
                            Imgproc.equalizeHist(frame_gray, frame_gray);
                            double w = frame.width();
                            double h = frame.height();
                            faceDetector.detectMultiScale(frame_gray, rostros, 1.1, 2, 0|CASCADE_SCALE_IMAGE, new Size(30, 30), new Size(w, h) );
                            facesArray = rostros.toArray();

                            for (int i = 0; i < facesArray.length; i++) {
                                Point center = new Point((facesArray[i].x + facesArray[i].width * 0.5), 
                                        (facesArray[i].y + facesArray[i].height * 0.5));

                                Mat faceROI = frame_gray.submat(facesArray[i]);
                                Imgproc.rectangle(frame,
                                        new Point(facesArray[i].x,facesArray[i].y),
                                        new Point(facesArray[i].x+facesArray[i].width,facesArray[i].y+facesArray[i].height),
                                        new Scalar(0, 0, 255), 3);
                            }

                            int no = facesArray.length;
                            lJumlah.setText("Faces detected " + String.valueOf(no));
                            
                            Imgcodecs.imencode(".bmp", frame, mem);
                            Image im = ImageIO.read(new ByteArrayInputStream(mem.toArray()));
                            buff = (BufferedImage) im;
                            if(g.drawImage(buff, 0, 0, lImage.getWidth(), lImage.getHeight() , 0, 0, buff.getWidth(), buff.getHeight(), null)){}
                        
                        } catch(Exception ex){
                            
                        }
                    }
                }

            }
        };
        wcam.start();
        bCam.setEnabled(false);
        bStop.setEnabled(true);
    }//GEN-LAST:event_bCamActionPerformed

    private void bStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStopActionPerformed

        capture.release();
        bCam.setEnabled(true);
        lImage.setIcon(null);
        lImage.setBackground(Color.white);
        lJumlah.setText("Faces detected 0");
        bStop.setEnabled(false);
        
    }//GEN-LAST:event_bStopActionPerformed

    private void bAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAboutActionPerformed
 
        String about = "Nama  : Muhammad Izzudin\nAbsen : 32602000047\n\n\nAplikasi ini menggunakan library OpenCV. "
                + "Library open source yang dikembangkan\noleh intel yang fokus untuk menyederhanakan programing "
                + "terkait citra digital.\nFiturnya yang dimiliki antara lain pengenalan wajah, pelacakan wajah, "
                + "deteksi wajah,\nKalman filtering, dan berbagai metode AI (Artificial Intellegence).\n\nSumber:\nhttps://codeguid.com/2019/08/11/opencv-face-detection-system-project-java/\nhttps://www.teachmeidea.com/2018/11/how-to-build-face-detection-app-in-java.html";
        JOptionPane.showMessageDialog(null, about);

    }//GEN-LAST:event_bAboutActionPerformed

    private void bCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCloseActionPerformed
        int option = JOptionPane.showConfirmDialog(null, "Are you sure?");
        switch(option) {
            case JOptionPane.YES_OPTION -> System.exit(0);
        }
    }//GEN-LAST:event_bCloseActionPerformed

    private void bSelectMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSelectMousePressed
        bSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button1hov.png")));
    }//GEN-LAST:event_bSelectMousePressed

    private void bSelectMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSelectMouseReleased
        bSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button1.png")));
    }//GEN-LAST:event_bSelectMouseReleased

    private void bCamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCamMousePressed
        bCam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button2hov.png")));
    }//GEN-LAST:event_bCamMousePressed

    private void bCamMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCamMouseReleased
        bCam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button2.png")));
    }//GEN-LAST:event_bCamMouseReleased

    private void bStartMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bStartMousePressed
        bStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button4hov.png")));
    }//GEN-LAST:event_bStartMousePressed

    private void bStartMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bStartMouseReleased
        bStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button4.png")));
    }//GEN-LAST:event_bStartMouseReleased

    private void bStopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bStopMousePressed
        bStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button3hov.png")));
    }//GEN-LAST:event_bStopMousePressed

    private void bStopMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bStopMouseReleased
        bStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button3.png")));
    }//GEN-LAST:event_bStopMouseReleased

    private void bCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCloseMousePressed
        bClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button6hov.png")));
    }//GEN-LAST:event_bCloseMousePressed

    private void bCloseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCloseMouseReleased
        bClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button6.png")));
    }//GEN-LAST:event_bCloseMouseReleased

    private void bAboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAboutMousePressed
        bAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button5hov.png")));
    }//GEN-LAST:event_bAboutMousePressed

    private void bAboutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAboutMouseReleased
        bAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button5.png")));
    }//GEN-LAST:event_bAboutMouseReleased

    private void bSelectMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSelectMouseEntered
        bSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button1en.png")));
    }//GEN-LAST:event_bSelectMouseEntered

    private void bSelectMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSelectMouseExited
        bSelect.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button1.png")));
    }//GEN-LAST:event_bSelectMouseExited

    private void bCamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCamMouseEntered
        bCam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button2en.png")));
    }//GEN-LAST:event_bCamMouseEntered

    private void bCamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCamMouseExited
        bCam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button2.png")));
    }//GEN-LAST:event_bCamMouseExited

    private void bStopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bStopMouseEntered
        bStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button3en.png")));
    }//GEN-LAST:event_bStopMouseEntered

    private void bStopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bStopMouseExited
        bStop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button3.png")));
    }//GEN-LAST:event_bStopMouseExited

    private void bStartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bStartMouseEntered
        bStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button4en.png")));
    }//GEN-LAST:event_bStartMouseEntered

    private void bStartMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bStartMouseExited
        bStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button4.png")));
    }//GEN-LAST:event_bStartMouseExited

    private void bAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAboutMouseEntered
        bAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button5en.png")));
    }//GEN-LAST:event_bAboutMouseEntered

    private void bAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAboutMouseExited
        bAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button5.png")));
    }//GEN-LAST:event_bAboutMouseExited

    private void bCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCloseMouseEntered
        bClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button6en.png")));
    }//GEN-LAST:event_bCloseMouseEntered

    private void bCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCloseMouseExited
        bClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button6.png")));
    }//GEN-LAST:event_bCloseMouseExited
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAbout;
    private javax.swing.JButton bCam;
    private javax.swing.JButton bClose;
    private javax.swing.JButton bSelect;
    private javax.swing.JButton bStart;
    private javax.swing.JButton bStop;
    private javax.swing.JTextField imgPath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lImage;
    private javax.swing.JLabel lJumlah;
    // End of variables declaration//GEN-END:variables
}
